[package]
name = "minitrace-jaeger"
version = "0.2.0"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2021"
description = "Jaeger reporter for minitrace-rust"
homepage = "https://github.com/tikv/minitrace-rust"
repository = "https://github.com/tikv/minitrace-rust"
documentation = "https://docs.rs/minitrace"
readme = "README.md"
keywords = ["tracing", "span", "datadog", "jaeger", "opentracing"]

[dependencies]
minitrace = { path = "../minitrace" }
thrift_codec = "0.1"

[dev-dependencies]
futures = "0.3"
